### ISSUE TITLE
To adjust  layout

### ISSUE THREAD

**Issue by 1F10230264** [tkmn1015/team-project#2]

**Comment by tkmn1015** [comment]
Please write the layout.

**Comment by 1F1022ES01** [comment]
Do you mean I need to create a example how our page could look like? 
ページがどのように見えるかサンプルを作成する必要があるということですか?

**Comment by 1F1022ES01** [comment]
[Wireframe for Web-site.pptx](https://github.com/tkmn1015/team-project/files/11845705/Wireframe.for.Web-site.pptx)


We can use this version.
