### ISSUE TITLE
Choose background for sub-pages (サブページの背景を選択する)

### ISSUE THREAD

**Issue by 1F1022ES01** [tkmn1015/team-project#5]
For other pages (for menu page, for page with information about shops)
その他のページへ（メニューページ、店舗情報ページ）

**Comment by otakota** [comment]
作ります

**Comment by 1F1022ES01** [comment]
I chose one and already have added it. Is it okay? Or we can choose another one
1 つを選択し、すでに追加しています。大丈夫ですか？または、別のものを選択することもできます

**Comment by 1F1022ES01** [comment]
Done
